global:
  smtp_smarthost: "smtp.qq.com:587"
  smtp_from: "your-alert-email@qq.com"
  smtp_auth_username: "your-alert-email@qq.com"
  smtp_auth_password: "your-smtp-password"
  resolve_timeout: 5m

templates:
  - "/etc/alertmanager/templates/*.tmpl"

route:
  group_by: ["alertname", "cluster", "service"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: "web.hook"
  routes:
    - match:
        severity: critical
      receiver: "web.hook"
      continue: true

receivers:
  - name: "web.hook"
    email_configs:
      - to: "admin@wuhao-tutor.com"
        headers:
          Subject: "五好伴学告警: {{ .GroupLabels.alertname }}"
        html: |
          {{ range .Alerts }}
          <p>告警名称: {{ .Annotations.summary }}</p>
          <p>告警详情: {{ .Annotations.description }}</p>
          <p>告警时间: {{ .StartsAt }}</p>
          {{ end }}

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]
